// Editorial topic map. Each entry pairs one homeowner question with a specific design consideration.
export const categories = [
{slug:'architectural-lighting',name:'Architectural lighting',intro:'Architectural lighting begins with the materials and shape of a home. These guides look at how to reveal form, texture, and entries without flattening everything into the same brightness.',image:'tudor-home.jpg',topics:[
['Brick facade lighting','Brick texture responds to grazing light, but fixture angle determines whether mortar joints look rich or overly sharp.','Compare the view from the street with the view from your front walk.'],
['Stone house uplighting','Uneven stone catches light differently across each surface, so a small aiming change can reshape the entire facade.','Look for dark gaps that add depth between illuminated features.'],
['Tudor home lighting','Timber, stucco, and stone create distinct surfaces that should not all receive the same intensity.','Decide whether the entry, roofline, or garden should be the first thing visitors notice.'],
['Front porch lighting','A porch needs a comfortable human scale as well as curb appeal; architectural accents should support the doorway.','Check for glare when seated on the porch and when arriving from the walk.'],
['Entry column lighting','Columns can frame an arrival, but broad, symmetrical beams may make a modest entry look too formal.','Test the effect on nearby doors, windows, and planting.'],
['Wall grazing versus washing','Grazing emphasizes texture while washing creates smoother, more even coverage; the material should guide the choice.','View a sample from several angles before repeating it across a wall.'],
['Historic home lighting','Older homes often have detailed masonry and irregular forms that look best with selective emphasis.','Protect the original character by keeping fixtures visually quiet in daylight.'],
['Modern facade lighting','Clean lines and broad surfaces often call for fewer, more deliberate focal points than a traditional facade.','Use planting and paths to soften the transition from house to landscape.']]},
{slug:'paths-and-steps',name:'Paths and steps',intro:'Paths and steps are experienced in motion. The strongest plan considers turns, grade changes, the surrounding planting, and how light appears from both directions.',image:'hillside-steps.jpg',topics:[
['Front walkway lighting','The walk to the door should be legible without becoming a runway of identical bright dots.','Prioritize turns, edges, and transitions rather than rigid spacing.'],
['Stone step lighting','Stone treads and risers create different opportunities for concealed or nearby illumination.','Check visibility while ascending and descending.'],
['Hillside path lighting','A sloped route changes the viewer height and can make an otherwise gentle fixture feel glaring.','Walk the route from top and bottom before choosing aim.'],
['Driveway edge lighting','A driveway approach benefits from visible cues at bends, planting islands, and the final turn toward the entry.','Separate navigation needs from decorative facade lighting.'],
['Garden path lighting','A garden route can use planted accents to suggest direction instead of lighting every inch of gravel or stone.','Preserve shadows so the garden retains depth.'],
['Retaining wall step lights','Walls can offer places for integrated light, but wall height and nearby steps determine where it is useful.','Consider drainage, access, and nighttime sightlines during planning.'],
['Walkway lighting on narrow lots','Urban properties have less room between fixture, path, and neighbor, increasing the importance of controlled output.','Check spill onto adjacent windows and sidewalks.'],
['Accessible route lighting','Consistent visual cues can help people read changes in level and direction on a familiar route.','Discuss the actual route and users rather than assuming one fixture pattern fits all.']]},
{slug:'patio-and-deck',name:'Patios and decks',intro:'Outdoor living lighting should help people gather, move, and enjoy the surrounding view. These guides consider the patio as an evening room with several layers.',image:'patio.jpg',topics:[
['Bluestone patio lighting','Bluestone has a subtle surface that can look flat under overhead brightness and richer with nearby planting accents.','Plan the seating view and the path back to the house together.'],
['Small patio lighting','A compact patio needs only a few carefully chosen points of light to feel complete.','Avoid placing a bright fixture at eye level beside the main seat.'],
['Deck step lighting','Deck stairs need a readable sequence of treads without bright spots that dominate the gathering area.','Evaluate the stairs from both the house and the yard.'],
['Pergola lighting','A pergola can hold gentle downlight while the surrounding garden adds depth beyond its posts.','Check how the overhead light affects conversation and views.'],
['Outdoor dining lighting','The table needs enough light for comfort, but the most inviting view may come from softly lit surroundings.','Balance meal lighting with a calm garden backdrop.'],
['Poolside landscape lighting','Lighting around water calls for careful attention to reflection, glare, and applicable electrical requirements.','Discuss the setting with qualified installers before selecting fixtures.'],
['Courtyard lighting','A courtyard can feel larger when a feature beyond the seating area is lit and walls retain some shadow.','Use brick or stone texture as part of the composition.'],
['Backyard entertaining zones','Dining, cooking, and quiet seating often need different light levels within one connected yard.','Map how guests move between zones after dark.']]},
{slug:'trees-and-gardens',name:'Trees and gardens',intro:'Plants are living architecture. A lighting plan should account for their shape today, how they grow, and the effect from the home as well as the yard.',image:'tree-lighting.jpg',topics:[
['Mature oak uplighting','A mature oak needs thoughtful beam placement to reveal branching without turning the canopy into a bright mass.','Stand far enough back to see the whole silhouette.'],
['Birch tree lighting','Pale birch trunks can become a strong vertical element with very little light.','Keep surrounding planting visible so the trunks do not float in darkness.'],
['Japanese maple lighting','A small sculptural tree can become a focal point when light catches the branching and seasonal foliage.','Allow for leaf color and density to change through the year.'],
['Evergreen lighting','Evergreens provide year-round structure, especially when deciduous beds are quiet in winter.','Avoid a flat cone of light by considering angle and nearby texture.'],
['Hydrangea bed lighting','Dense summer blooms can hide fixtures and change the way light spreads through a border.','Leave access for later adjustment as the plants fill in.'],
['Ornamental grass lighting','Grasses can glow with backlight or edge light, but their movement and seasonal cutback matter.','Review the scene in both growing and dormant seasons.'],
['Garden wall and planting','Lighting a wall behind planting can create a second layer without flooding the bed itself.','Check the wall texture and the shadows cast by mature leaves.'],
['Specimen tree placement','A focal tree should relate to the house, path, and primary indoor view rather than stand alone.','Choose the viewpoint before choosing the fixture location.']]},
{slug:'low-voltage-systems',name:'Low-voltage systems',intro:'A low-voltage system is a connected design, not a collection of independent lights. These guides explain questions about fixtures, controls, and future care at a homeowner level.',image:'fixture-detail.jpg',topics:[
['How low-voltage lighting works','A transformer supplies a lower-voltage circuit to outdoor fixtures, with layout influencing performance and service access.','Ask how the proposed layout will be maintained as the landscape grows.'],
['Choosing a lighting transformer','Transformer capacity and location should suit the system design and access needs.','Do not select a unit from fixture count alone without a complete plan.'],
['Lighting timers and controls','Controls determine when the scene appears and can make a beautiful design easier to live with.','Consider dusk timing, travel routines, and seasonal changes.'],
['Warm versus cool light','Color temperature changes the mood of brick, stone, wood, and plants even when brightness stays similar.','Compare samples on your actual materials after dark.'],
['Beam spread explained','A narrow beam can isolate an element while a wider beam covers more surface with a different visual character.','Match the beam to the feature and viewing distance.'],
['Fixture placement basics','A fixture should be positioned for the desired effect and to avoid direct glare from common viewpoints.','Check the view from windows as well as the sidewalk.'],
['Outdoor lighting wiring questions','Wire routes affect installation, future planting, and access for service.','Discuss where beds, hardscape, and utilities limit a route.'],
['LED landscape lighting','LED fixtures can provide efficient long-term illumination, but design quality still depends on placement and aiming.','Judge the nighttime composition, not only the fixture specification.']]},
{slug:'installation-planning',name:'Installation planning',intro:'Good installation starts before a fixture goes into the ground. The property, access, existing hardscape, and desired nighttime effect all shape the plan.',image:'garden-stone-steps.jpg',topics:[
['Preparing for a lighting consultation','Photos, a short list of priorities, and notes about current problem areas make the first conversation more useful.','Walk the property at night and record the views that matter.'],
['Lighting design walkthrough','A walkthrough should connect your goals with real sightlines, grade, planting, and entry routes.','Point out how you use the space, not only what you want lit.'],
['Installing around existing planting','Mature beds can offer beautiful layers but leave little room for fixture and wire placement.','Discuss protection of roots and access before work begins.'],
['Lighting around new landscaping','A new landscape can be planned with future lighting in mind, even while plants are small.','Allow for growth instead of aiming only at today\'s size.'],
['Working with stone hardscape','Existing steps and walls may offer lighting opportunities, but material and access affect the installation approach.','Ask what can be done without disrupting valued surfaces.'],
['Planning for future expansion','A phased project can begin with the highest-value areas while anticipating later patio or garden work.','Identify likely future routes before the first installation.'],
['Testing a lighting scene at night','The effect is best judged from real viewpoints after dark, when glare and dark gaps are visible.','Review street, path, patio, and interior views.'],
['Final aiming and adjustments','Small changes in angle can improve a whole scene after fixtures are installed.','Leave time to look at the finished composition after sunset.']]},
{slug:'maintenance-and-service',name:'Maintenance and service',intro:'Outdoor lighting sits among weather, soil, and growing plants. These guides help homeowners notice changes and ask useful service questions without guessing at electrical work.',image:'fixture-detail.jpg',topics:[
['When a path light goes dark','A dark fixture can have several causes, from a simple local issue to a broader system concern.','Note whether nearby lights on the same route are affected.'],
['Tree growth and fixture aiming','As branches and foliage grow, an uplight may hit a different surface than it did originally.','Review the tree silhouette from your regular evening view.'],
['Cleaning landscape fixtures','Soil, leaves, and debris can change the light pattern or hide a fixture.','Use the manufacturer\'s care guidance and avoid disturbing wiring.'],
['Seasonal lighting checkup','A seasonal review catches plant growth, shifted fixtures, and changed control timing.','Photograph the scene from consistent viewpoints over time.'],
['Refreshing an older system','An older system may benefit from targeted repairs, new aiming, or a broader redesign.','Describe what still works well before deciding what to replace.'],
['Troubleshooting uneven brightness','Uneven output can relate to layout, fixture condition, or the way the scene is aimed.','Compare the effect at the beginning and end of each run.'],
['Storm and weather follow-up','After severe weather, look for displaced fixtures and obvious damage without handling exposed wiring.','Contact a qualified professional for electrical concerns.'],
['Service for another installer’s system','Existing systems can sometimes be evaluated and improved regardless of who installed them.','Share age, photos, and symptoms before a visit.']]},
{slug:'cost-and-project-scope',name:'Cost and project scope',intro:'Project scope is driven by property size, complexity, fixture selection, and the areas you choose to prioritize. These guides help frame a useful estimate conversation.',image:'stone-entry.jpg',topics:[
['What affects landscape lighting cost','Access, hardscape, system complexity, and the number of distinct scenes all affect a proposal.','Compare the design and included work, not just fixture count.'],
['Starting with the front entry','An entry-focused phase can create a clear arrival experience while leaving room to expand later.','Include the walk and immediate planting in the first conversation.'],
['Phasing a whole-property design','A master plan can help separate immediate priorities from future garden or patio phases.','Think about infrastructure that future phases may share.'],
['Comparing lighting estimates','Two proposals may differ in design intent, materials, controls, and service expectations.','Ask each provider to explain what the nighttime scene will look like.'],
['How many fixtures are enough','More fixtures are not automatically better; placement and beam choice often matter more.','Ask what each proposed fixture is meant to reveal.'],
['Value of a nighttime walkthrough','Seeing the property after dark can reveal priorities that daylight photos miss.','Discuss what you find difficult to see and what you want to enjoy.'],
['Budgeting for service','A lighting system benefits from occasional review as plants grow and conditions change.','Ask what ongoing care and adjustments may be needed.'],
['Choosing an initial project area','The best first area is usually the space you use or see most often.','Rank front arrival, outdoor living, and interior views.']]},
{slug:'pittsburgh-property-guide',name:'Pittsburgh property guide',intro:'Pittsburgh properties often combine brick or stone architecture with slopes, mature trees, and compact urban lots. These guides focus on those physical design conditions without pretending one neighborhood has one standard solution.',image:'shadyside-brick-home.jpg',topics:[
['Lighting a sloped Pittsburgh yard','Grade changes create both dramatic views and unusual glare angles.','Review the design from above and below each major slope.'],
['Brick rowhouse garden lighting','A narrow garden needs careful control of wall reflections and neighboring windows.','Choose a primary view before placing multiple bright accents.'],
['Stone retaining wall lighting','Local stone walls can become a visual layer while also defining a route.','Consider wall texture, drainage, and the path beside it.'],
['Mature street tree lighting','A large street tree can frame an approach, but placement may be constrained by public space and utilities.','Confirm permissions and ownership before planning fixtures.'],
['Narrow city lot lighting','Limited width makes light spill and fixture visibility more noticeable.','Use a few deliberate focal points and check neighboring sightlines.'],
['Suburban wooded property lighting','A wooded setting benefits from selective depth rather than trying to illuminate the entire tree line.','Choose a few trunks or canopies that compose a view.'],
['Older front porch and steps','Historic porches and irregular steps create useful lighting opportunities and installation constraints.','Keep fixtures compatible with the home\'s character.'],
['Four-season landscape lighting','Deciduous gardens change dramatically between summer and winter.','Plan a scene with evergreen structure and architectural elements too.']]},
{slug:'lighting-design-principles',name:'Lighting design principles',intro:'The best lighting feels calm because every fixture has a job. These guides explain the design choices behind depth, balance, warmth, and an inviting evening view.',image:'oak-uplighting.jpg',topics:[
['Layering outdoor light','Foreground paths, midground planting, and distant trees can create depth without raising overall brightness.','Identify the view where those layers should work together.'],
['Avoiding outdoor glare','Direct view of a bright source can overpower a carefully lit scene.','Check seated, walking, and indoor viewpoints.'],
['Using darkness intentionally','Shadows give lit features shape and let the eye rest between focal points.','Decide what can remain dark before adding another fixture.'],
['Choosing a focal point','A doorway, tree, or stone feature can anchor an evening view.','Let secondary lighting support rather than compete with it.'],
['Balancing symmetry and nature','A symmetrical facade may benefit from balance, while planting usually looks better with a looser rhythm.','Design for the whole view rather than repeating one fixture pattern.'],
['Lighting views from indoors','Outdoor lighting can extend the visual space of a room after dark.','Stand at the windows you use most when reviewing the plan.'],
['Color consistency outdoors','Mixed light colors can make surfaces feel disconnected even when fixture placement is good.','Look at the entire composition after sunset.'],
['Creating a warm welcome','Arrival lighting combines a readable route with a sense of hospitality.','Consider the transition from the street all the way to the door.']]},
{slug:'seasonal-outdoor-lighting',name:'Seasonal outdoor lighting',intro:'Plants, sunset time, and how people use outdoor space change through the year. These guides help a permanent lighting plan stay useful in every season.',image:'winter-home.jpg',topics:[
['Spring garden lighting','New foliage changes how light passes through beds and reveals fixtures.','Check aiming as growth resumes.'],
['Summer patio evenings','Longer evenings and full planting create an outdoor room with dense edges.','Review glare from seated positions when foliage is at its fullest.'],
['Autumn tree lighting','Color and thinning canopies change the effect of tree uplighting.','Look for branches that become newly visible as leaves fall.'],
['Winter landscape lighting','Evergreens, masonry, and paths carry the scene when summer planting disappears.','Plan some year-round structure rather than relying only on blooms.'],
['Lighting after snow','Snow reflects more light and can alter how a familiar scene feels.','Keep paths legible without trying to over-light the whole yard.'],
['Daylight-saving time changes','Control schedules may need attention when daylight hours change.','Check that lights turn on when your evening routine begins.'],
['Holiday lighting with permanent fixtures','Permanent landscape lighting can provide a calm backdrop for temporary decoration.','Avoid competing colors and bright focal points.'],
['End-of-season system review','A short review can identify shifted fixtures, overgrowth, and changing priorities.','Record the views you want to improve next year.']]},
{slug:'homeowner-questions',name:'Homeowner questions',intro:'A good first conversation should leave you clearer about design, installation, and care. These guides turn common homeowner questions into practical things to inspect or ask.',image:'front-steps.jpg',topics:[
['Is landscape lighting worth it','Value depends on how often you use and see the spaces being lit.','Start with a specific evening experience you want to improve.'],
['Will lighting bother neighbors','Poor aiming can spill light into nearby windows; a careful design considers shared sightlines.','Review the scene from the property edge.'],
['Can existing lighting be improved','An existing system may offer a useful starting point even if the current effect feels uneven.','Note what you like before discussing changes.'],
['How bright should path lights be','Brightness should help you read the route without dominating the garden.','Test the route with nearby architectural lights on.'],
['Do I need lighting in every area','Most properties benefit from prioritizing the routes and views that matter most.','Leave less-used areas quiet if they do not support the composition.'],
['Can lighting be added later','A phased plan can allow future areas to be considered during initial design.','Mention likely patio or landscape changes early.'],
['How do I choose a lighting designer','Ask to understand the provider\'s design process, nighttime review, and ongoing service.','Look for a clear explanation of why each area is lit.'],
['What photos should I share','Daytime and nighttime views from important positions help explain a property quickly.','Include the street, main walk, patio, and troublesome dark areas.']]},
{slug:'lighting-comparisons',name:'Lighting comparisons',intro:'Different fixtures and approaches can solve similar problems with different visual results. These comparisons focus on what a homeowner will actually see and experience.',image:'bluestone-patio.jpg',topics:[
['Path lights versus step lights','Path lights illuminate a route and nearby planting, while step lights emphasize level changes.','Choose based on the surface and the transition you need to read.'],
['Uplighting versus downlighting','Uplighting reveals form from below; downlighting can create a softer pool from above.','Consider fixture visibility and the natural shape of the feature.'],
['Grazing versus washing brick','Grazing makes masonry texture pronounced, while washing produces a more even facade.','Compare both effects on the actual wall.'],
['Warm white versus cool white','Warmer light often suits brick and wood; cooler light changes the visual temperature of surfaces.','Judge samples at night next to existing exterior lights.'],
['Garden accents versus floodlights','Selective accents create layers, while a floodlight tends to flatten large areas.','Define which features deserve attention.'],
['Permanent versus temporary lighting','Permanent landscape lighting supports everyday routes and views; temporary lighting can be event-specific.','Plan the everyday scene first.'],
['Integrated versus freestanding fixtures','Integrated fixtures can disappear into a wall or step, while freestanding ones offer different flexibility.','Consider access and future adjustments.'],
['Front yard versus backyard priorities','The front often centers on arrival, while the back may center on time spent outside.','Choose the phase that improves daily life most.']]}
];
